# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'MarchInterviewPractice' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MarchInterviewPractice
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'SWXMLHash', '~> 4.7.0'
pod 'AlamofireImage', '~> 3.5'

  target 'MarchInterviewPracticeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MarchInterviewPracticeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
